import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇬🇧', dir: 'ltr' },
  { code: 'fr', label: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'es', label: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'ko', label: '한국어', flag: '🇰🇷', dir: 'ltr' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦', dir: 'rtl' },
];

export const TRANSLATIONS = {
  en: {
    // Splash
    splash_tagline: 'Watch ads. Feed dogs. Change lives.',
    splash_cta: 'Get Started 🐾',
    splash_free: 'Free to join · No credit card needed',
    splash_real: 'Real dogs. Real meals.',
    splash_choose_language: 'Choose your language',
    // Register
    step_of: 'Step {step} of {total}',
    why_title: 'Why do we ask this?',
    why_body: 'The more we know about you, the more relevant and valuable ads we can show. Advertisers pay significantly more for targeted audiences — which means every extra data point directly translates into more meals for stray dogs. A fully detailed profile can generate up to 4× more food than a basic one.',
    // Step 1
    basic_info: 'Basic Information',
    display_name: 'Display Name',
    display_name_placeholder: 'How should we call you?',
    age_range: 'Age Range',
    age_range_placeholder: 'Select age range',
    country: 'Country',
    country_placeholder: 'Select country',
    // Step 2
    about_life: 'About Your Life',
    about_life_sub: 'Household info helps advertisers match the right products to you',
    gender: 'Gender',
    male: 'Male', female: 'Female', non_binary: 'Non-binary', prefer_not: 'Prefer not to say',
    rel_status: 'Relationship Status',
    rel_placeholder: 'Select status',
    single: 'Single', in_rel: 'In a relationship', married: 'Married / Partnered', divorced: 'Divorced / Separated',
    employment: 'Employment Status',
    student: 'Student', employed_ft: 'Employed full-time', employed_pt: 'Employed part-time',
    self_emp: 'Self-employed / Freelance', unemployed: 'Unemployed', retired: 'Retired',
    household: 'Household Size',
    household_placeholder: 'People in your household',
    just_me: 'Just me', two_people: '2 people', three_four: '3–4 people', five_plus: '5 or more',
    income: 'Annual Household Income',
    income_placeholder: 'Select range (optional)',
    // Step 3
    interests_values: 'Interests & Values',
    interests_sub: 'Select at least 2 from each section — this unlocks premium ad revenue',
    what_interests: 'What interests you?',
    what_values: 'What do you value most in life?',
    // Step 4
    lifestyle: 'Your Lifestyle',
    lifestyle_sub: 'Lifestyle data helps brands find the perfect audience — more targeted = higher ad value = more dog food',
    which_best: 'Which best describes you?',
    shop_freq: 'How often do you shop online?',
    shop_placeholder: 'Select frequency',
    daily: 'Almost daily', weekly: 'A few times a week', monthly: 'A few times a month', rarely: 'Rarely',
    primary_device: 'Primary device you use',
    device_placeholder: 'Select device',
    screen_time: 'Daily screen time',
    screen_placeholder: 'Select screen time',
    under_1h: 'Under 1 hour', h_1_3: '1–3 hours', h_3_5: '3–5 hours', over_5h: 'Over 5 hours',
    // Step 5
    shopping_intent: 'Shopping & Buying Intent',
    shopping_sub: 'This is the highest-value data for advertisers — it directly feeds more dogs! 🐕',
    where_shop: 'Where do you prefer to shop?',
    buy_next: 'What are you likely to buy in the next 3 months?',
    social_platforms: 'Which social platforms do you use?',
    privacy_note: '🔒 Your data is never sold. It\'s used only to show you more relevant ads so advertisers pay more — meaning more meals for stray dogs worldwide.',
    // Buttons
    continue: 'Continue',
    back: 'Back',
    start: 'Start Feeding Dogs! 🐕',
    saving: 'Saving...',
    // Lifestyle options
    homebody: '🏠 Homebody', homebody_d: 'Love cosy nights in',
    adventurer: '🧗 Adventurer', adventurer_d: 'Always seeking thrills',
    social_butterfly: '🦋 Social butterfly', social_butterfly_d: 'Love being around people',
    wellness: '🧘 Wellness focused', wellness_d: 'Health & mindfulness first',
    career: '🚀 Career driven', career_d: 'Ambitious & goal-oriented',
    family: '👨‍👩‍👧 Family first', family_d: 'Family is everything',
  },
  fr: {
    splash_tagline: 'Regardez des pubs. Nourrissez des chiens. Changez des vies.',
    splash_cta: 'Commencer 🐾',
    splash_free: 'Gratuit · Sans carte bancaire',
    splash_real: 'De vrais chiens. De vrais repas.',
    splash_choose_language: 'Choisissez votre langue',
    step_of: 'Étape {step} sur {total}',
    why_title: 'Pourquoi nous demandons cela ?',
    why_body: 'Plus nous vous connaissons, plus nous pouvons afficher des publicités pertinentes. Les annonceurs paient beaucoup plus pour des audiences ciblées — chaque donnée se traduit directement en repas pour les chiens errants. Un profil complet peut générer jusqu\'à 4× plus de nourriture.',
    basic_info: 'Informations de base',
    display_name: 'Nom affiché',
    display_name_placeholder: 'Comment vous appeler ?',
    age_range: 'Tranche d\'âge',
    age_range_placeholder: 'Sélectionnez votre tranche d\'âge',
    country: 'Pays',
    country_placeholder: 'Sélectionnez votre pays',
    about_life: 'Votre vie',
    about_life_sub: 'Ces infos aident les annonceurs à vous proposer les bons produits',
    gender: 'Genre',
    male: 'Homme', female: 'Femme', non_binary: 'Non-binaire', prefer_not: 'Préfère ne pas dire',
    rel_status: 'Situation amoureuse',
    rel_placeholder: 'Sélectionnez',
    single: 'Célibataire', in_rel: 'En couple', married: 'Marié(e) / Pacsé(e)', divorced: 'Divorcé(e) / Séparé(e)',
    employment: 'Situation professionnelle',
    student: 'Étudiant(e)', employed_ft: 'Employé(e) à temps plein', employed_pt: 'Employé(e) à temps partiel',
    self_emp: 'Indépendant(e) / Freelance', unemployed: 'Sans emploi', retired: 'Retraité(e)',
    household: 'Taille du foyer',
    household_placeholder: 'Personnes dans votre foyer',
    just_me: 'Juste moi', two_people: '2 personnes', three_four: '3–4 personnes', five_plus: '5 ou plus',
    income: 'Revenu annuel du foyer',
    income_placeholder: 'Sélectionner (facultatif)',
    interests_values: 'Intérêts & Valeurs',
    interests_sub: 'Sélectionnez au moins 2 de chaque section',
    what_interests: 'Qu\'est-ce qui vous intéresse ?',
    what_values: 'Qu\'est-ce que vous valorisez le plus dans la vie ?',
    lifestyle: 'Votre style de vie',
    lifestyle_sub: 'Ces données aident les marques à trouver leur audience idéale',
    which_best: 'Lequel vous décrit le mieux ?',
    shop_freq: 'À quelle fréquence achetez-vous en ligne ?',
    shop_placeholder: 'Sélectionner la fréquence',
    daily: 'Presque chaque jour', weekly: 'Quelques fois par semaine', monthly: 'Quelques fois par mois', rarely: 'Rarement',
    primary_device: 'Appareil principal',
    device_placeholder: 'Sélectionnez l\'appareil',
    screen_time: 'Temps d\'écran quotidien',
    screen_placeholder: 'Sélectionner',
    under_1h: 'Moins d\'1 heure', h_1_3: '1–3 heures', h_3_5: '3–5 heures', over_5h: 'Plus de 5 heures',
    shopping_intent: 'Achats & Intentions',
    shopping_sub: 'Ce sont les données les plus précieuses — elles nourrissent directement plus de chiens ! 🐕',
    where_shop: 'Où préférez-vous acheter ?',
    buy_next: 'Qu\'allez-vous probablement acheter dans les 3 prochains mois ?',
    social_platforms: 'Quelles plateformes sociales utilisez-vous ?',
    privacy_note: '🔒 Vos données ne sont jamais vendues. Elles servent uniquement à afficher des publicités plus pertinentes.',
    continue: 'Continuer',
    back: 'Retour',
    start: 'Commencer à nourrir ! 🐕',
    saving: 'Sauvegarde...',
    homebody: '🏠 Casanier', homebody_d: 'J\'aime les soirées cosy',
    adventurer: '🧗 Aventurier', adventurer_d: 'Toujours en quête de sensations',
    social_butterfly: '🦋 Papillon social', social_butterfly_d: 'J\'adore être entouré(e)',
    wellness: '🧘 Bien-être', wellness_d: 'Santé & pleine conscience en premier',
    career: '🚀 Carriériste', career_d: 'Ambitieux et orienté objectifs',
    family: '👨‍👩‍👧 Famille avant tout', family_d: 'La famille, c\'est tout',
  },
  de: {
    splash_tagline: 'Werbung schauen. Hunde füttern. Leben verändern.',
    splash_cta: 'Loslegen 🐾',
    splash_free: 'Kostenlos · Keine Kreditkarte',
    splash_real: 'Echte Hunde. Echte Mahlzeiten.',
    splash_choose_language: 'Sprache wählen',
    step_of: 'Schritt {step} von {total}',
    why_title: 'Warum fragen wir das?',
    why_body: 'Je mehr wir über Sie wissen, desto relevanter und wertvoller sind die Anzeigen. Werbetreibende zahlen deutlich mehr für zielgerichtete Zielgruppen — jeder Datenpunkt bedeutet mehr Mahlzeiten für streunende Hunde.',
    basic_info: 'Grundlegende Informationen',
    display_name: 'Anzeigename',
    display_name_placeholder: 'Wie sollen wir Sie nennen?',
    age_range: 'Altersgruppe',
    age_range_placeholder: 'Altersgruppe wählen',
    country: 'Land',
    country_placeholder: 'Land wählen',
    about_life: 'Über Ihr Leben',
    about_life_sub: 'Haushaltsdaten helfen Werbetreibenden, die richtigen Produkte zu empfehlen',
    gender: 'Geschlecht',
    male: 'Männlich', female: 'Weiblich', non_binary: 'Nicht-binär', prefer_not: 'Keine Angabe',
    rel_status: 'Beziehungsstatus',
    rel_placeholder: 'Status wählen',
    single: 'Single', in_rel: 'In einer Beziehung', married: 'Verheiratet / Partner', divorced: 'Geschieden / Getrennt',
    employment: 'Beschäftigungsstatus',
    student: 'Student/in', employed_ft: 'Vollzeitbeschäftigt', employed_pt: 'Teilzeitbeschäftigt',
    self_emp: 'Selbstständig / Freiberufler', unemployed: 'Arbeitslos', retired: 'Rentner/in',
    household: 'Haushaltsgröße',
    household_placeholder: 'Personen im Haushalt',
    just_me: 'Nur ich', two_people: '2 Personen', three_four: '3–4 Personen', five_plus: '5 oder mehr',
    income: 'Jährliches Haushaltseinkommen',
    income_placeholder: 'Bereich wählen (optional)',
    interests_values: 'Interessen & Werte',
    interests_sub: 'Wählen Sie mindestens 2 aus jedem Bereich',
    what_interests: 'Was interessiert Sie?',
    what_values: 'Was ist Ihnen im Leben am wichtigsten?',
    lifestyle: 'Ihr Lebensstil',
    lifestyle_sub: 'Lifestyle-Daten helfen Marken, die perfekte Zielgruppe zu finden',
    which_best: 'Was beschreibt Sie am besten?',
    shop_freq: 'Wie oft kaufen Sie online ein?',
    shop_placeholder: 'Häufigkeit wählen',
    daily: 'Fast täglich', weekly: 'Ein paar Mal pro Woche', monthly: 'Ein paar Mal pro Monat', rarely: 'Selten',
    primary_device: 'Hauptgerät',
    device_placeholder: 'Gerät wählen',
    screen_time: 'Tägliche Bildschirmzeit',
    screen_placeholder: 'Bildschirmzeit wählen',
    under_1h: 'Unter 1 Stunde', h_1_3: '1–3 Stunden', h_3_5: '3–5 Stunden', over_5h: 'Über 5 Stunden',
    shopping_intent: 'Einkauf & Kaufabsicht',
    shopping_sub: 'Das sind die wertvollsten Daten — sie füttern direkt mehr Hunde! 🐕',
    where_shop: 'Wo kaufen Sie am liebsten ein?',
    buy_next: 'Was werden Sie wahrscheinlich in den nächsten 3 Monaten kaufen?',
    social_platforms: 'Welche sozialen Plattformen nutzen Sie?',
    privacy_note: '🔒 Ihre Daten werden niemals verkauft. Sie dienen nur dazu, relevantere Anzeigen zu zeigen.',
    continue: 'Weiter',
    back: 'Zurück',
    start: 'Hunde füttern! 🐕',
    saving: 'Speichern...',
    homebody: '🏠 Heimmensch', homebody_d: 'Liebe gemütliche Abende zuhause',
    adventurer: '🧗 Abenteurer', adventurer_d: 'Immer auf der Suche nach Nervenkitzel',
    social_butterfly: '🦋 Gesellschaftsmensch', social_butterfly_d: 'Liebe es, unter Menschen zu sein',
    wellness: '🧘 Gesundheitsbewusst', wellness_d: 'Gesundheit & Achtsamkeit zuerst',
    career: '🚀 Karriereorientiert', career_d: 'Ehrgeizig und zielorientiert',
    family: '👨‍👩‍👧 Familie zuerst', family_d: 'Familie ist alles',
  },
  es: {
    splash_tagline: 'Mira anuncios. Alimenta perros. Cambia vidas.',
    splash_cta: 'Empezar 🐾',
    splash_free: 'Gratis · Sin tarjeta de crédito',
    splash_real: 'Perros reales. Comidas reales.',
    splash_choose_language: 'Elige tu idioma',
    step_of: 'Paso {step} de {total}',
    why_title: '¿Por qué preguntamos esto?',
    why_body: 'Cuanto más te conocemos, más relevantes son los anuncios. Los anunciantes pagan mucho más por audiencias segmentadas — cada dato se traduce directamente en más comida para los perros callejeros.',
    basic_info: 'Información básica',
    display_name: 'Nombre mostrado',
    display_name_placeholder: '¿Cómo te llamamos?',
    age_range: 'Rango de edad',
    age_range_placeholder: 'Selecciona tu rango de edad',
    country: 'País',
    country_placeholder: 'Selecciona tu país',
    about_life: 'Tu vida',
    about_life_sub: 'Esta información ayuda a los anunciantes a recomendarte los productos adecuados',
    gender: 'Género',
    male: 'Hombre', female: 'Mujer', non_binary: 'No binario', prefer_not: 'Prefiero no decir',
    rel_status: 'Estado civil',
    rel_placeholder: 'Selecciona',
    single: 'Soltero/a', in_rel: 'En pareja', married: 'Casado/a', divorced: 'Divorciado/a',
    employment: 'Situación laboral',
    student: 'Estudiante', employed_ft: 'Empleado a tiempo completo', employed_pt: 'Empleado a tiempo parcial',
    self_emp: 'Autónomo / Freelance', unemployed: 'Desempleado', retired: 'Jubilado/a',
    household: 'Tamaño del hogar',
    household_placeholder: 'Personas en tu hogar',
    just_me: 'Solo yo', two_people: '2 personas', three_four: '3–4 personas', five_plus: '5 o más',
    income: 'Ingresos anuales del hogar',
    income_placeholder: 'Seleccionar (opcional)',
    interests_values: 'Intereses & Valores',
    interests_sub: 'Selecciona al menos 2 de cada sección',
    what_interests: '¿Qué te interesa?',
    what_values: '¿Qué valoras más en la vida?',
    lifestyle: 'Tu estilo de vida',
    lifestyle_sub: 'Estos datos ayudan a las marcas a encontrar la audiencia perfecta',
    which_best: '¿Cuál te describe mejor?',
    shop_freq: '¿Con qué frecuencia compras online?',
    shop_placeholder: 'Selecciona frecuencia',
    daily: 'Casi a diario', weekly: 'Varias veces a la semana', monthly: 'Varias veces al mes', rarely: 'Raramente',
    primary_device: 'Dispositivo principal',
    device_placeholder: 'Selecciona dispositivo',
    screen_time: 'Tiempo de pantalla diario',
    screen_placeholder: 'Seleccionar',
    under_1h: 'Menos de 1 hora', h_1_3: '1–3 horas', h_3_5: '3–5 horas', over_5h: 'Más de 5 horas',
    shopping_intent: 'Compras & Intención de compra',
    shopping_sub: 'Estos son los datos más valiosos — ¡alimentan directamente a más perros! 🐕',
    where_shop: '¿Dónde prefieres comprar?',
    buy_next: '¿Qué vas a comprar probablemente en los próximos 3 meses?',
    social_platforms: '¿Qué plataformas sociales usas?',
    privacy_note: '🔒 Tus datos nunca se venden. Solo se usan para mostrarte anuncios más relevantes.',
    continue: 'Continuar',
    back: 'Atrás',
    start: '¡Empezar a alimentar! 🐕',
    saving: 'Guardando...',
    homebody: '🏠 Hogareño', homebody_d: 'Amo las noches en casa',
    adventurer: '🧗 Aventurero', adventurer_d: 'Siempre buscando emociones',
    social_butterfly: '🦋 Mariposa social', social_butterfly_d: 'Me encanta estar con gente',
    wellness: '🧘 Bienestar', wellness_d: 'Salud y mindfulness primero',
    career: '🚀 Orientado a la carrera', career_d: 'Ambicioso y con metas',
    family: '👨‍👩‍👧 Familia primero', family_d: 'La familia lo es todo',
  },
  ko: {
    splash_tagline: '광고 보기. 유기견 먹이기. 삶을 바꾸기.',
    splash_cta: '시작하기 🐾',
    splash_free: '무료 가입 · 신용카드 불필요',
    splash_real: '실제 강아지들. 실제 밥.',
    splash_choose_language: '언어를 선택하세요',
    step_of: '{step} / {total} 단계',
    why_title: '왜 이것을 묻나요?',
    why_body: '우리가 당신에 대해 더 많이 알수록, 더 관련성 높은 광고를 보여줄 수 있습니다. 광고주들은 타겟팅된 청중에게 훨씬 더 많은 금액을 지불합니다 — 이는 유기견에게 더 많은 밥을 의미합니다.',
    basic_info: '기본 정보',
    display_name: '표시 이름',
    display_name_placeholder: '어떻게 불러드릴까요?',
    age_range: '연령대',
    age_range_placeholder: '연령대 선택',
    country: '국가',
    country_placeholder: '국가 선택',
    about_life: '내 생활',
    about_life_sub: '가구 정보는 광고주가 적합한 제품을 추천하는 데 도움이 됩니다',
    gender: '성별',
    male: '남성', female: '여성', non_binary: '논바이너리', prefer_not: '응답 거부',
    rel_status: '연애 상태',
    rel_placeholder: '선택하세요',
    single: '싱글', in_rel: '연인 있음', married: '기혼 / 동반자', divorced: '이혼 / 별거',
    employment: '취업 상태',
    student: '학생', employed_ft: '정규직', employed_pt: '파트타임',
    self_emp: '자영업 / 프리랜서', unemployed: '미취업', retired: '은퇴',
    household: '가구 규모',
    household_placeholder: '가구 내 인원',
    just_me: '혼자', two_people: '2명', three_four: '3–4명', five_plus: '5명 이상',
    income: '연간 가구 소득',
    income_placeholder: '범위 선택 (선택사항)',
    interests_values: '관심사 & 가치관',
    interests_sub: '각 섹션에서 최소 2개 선택하세요',
    what_interests: '무엇에 관심이 있나요?',
    what_values: '삶에서 가장 중요하게 생각하는 것은?',
    lifestyle: '생활 방식',
    lifestyle_sub: '이 데이터는 브랜드가 완벽한 청중을 찾는 데 도움이 됩니다',
    which_best: '나를 가장 잘 설명하는 것은?',
    shop_freq: '온라인 쇼핑 빈도는?',
    shop_placeholder: '빈도 선택',
    daily: '거의 매일', weekly: '주 몇 번', monthly: '월 몇 번', rarely: '드물게',
    primary_device: '주로 사용하는 기기',
    device_placeholder: '기기 선택',
    screen_time: '하루 스크린 타임',
    screen_placeholder: '스크린 타임 선택',
    under_1h: '1시간 미만', h_1_3: '1–3시간', h_3_5: '3–5시간', over_5h: '5시간 이상',
    shopping_intent: '쇼핑 & 구매 의도',
    shopping_sub: '이것이 광고주에게 가장 가치 있는 데이터입니다 — 더 많은 강아지를 직접 먹입니다! 🐕',
    where_shop: '어디서 쇼핑하는 걸 선호하나요?',
    buy_next: '앞으로 3개월 안에 무엇을 살 것 같나요?',
    social_platforms: '어떤 소셜 플랫폼을 사용하나요?',
    privacy_note: '🔒 내 데이터는 절대 판매되지 않습니다. 더 관련성 높은 광고를 보여주기 위해서만 사용됩니다.',
    continue: '계속',
    back: '뒤로',
    start: '강아지 먹이기 시작! 🐕',
    saving: '저장 중...',
    homebody: '🏠 집돌이/집순이', homebody_d: '아늑한 집에서의 밤을 좋아해요',
    adventurer: '🧗 모험가', adventurer_d: '항상 새로운 스릴을 추구해요',
    social_butterfly: '🦋 사교적인 사람', social_butterfly_d: '사람들과 함께하는 걸 좋아해요',
    wellness: '🧘 웰니스 지향', wellness_d: '건강과 마음챙김을 우선해요',
    career: '🚀 커리어 지향', career_d: '야망 있고 목표 지향적이에요',
    family: '👨‍👩‍👧 가족 우선', family_d: '가족이 전부예요',
  },
  ar: {
    splash_tagline: 'شاهد الإعلانات. أطعم الكلاب. غيّر الحياة.',
    splash_cta: 'ابدأ الآن 🐾',
    splash_free: 'مجاني · بدون بطاقة ائتمان',
    splash_real: 'كلاب حقيقية. وجبات حقيقية.',
    splash_choose_language: 'اختر لغتك',
    step_of: 'الخطوة {step} من {total}',
    why_title: 'لماذا نسأل عن هذا؟',
    why_body: 'كلما عرفنا عنك أكثر، كلما أمكننا عرض إعلانات أكثر صلة وقيمة. يدفع المعلنون أكثر بكثير للجماهير المستهدفة — وهذا يعني المزيد من الوجبات للكلاب الضالة.',
    basic_info: 'معلومات أساسية',
    display_name: 'الاسم المعروض',
    display_name_placeholder: 'كيف نناديك؟',
    age_range: 'الفئة العمرية',
    age_range_placeholder: 'اختر الفئة العمرية',
    country: 'الدولة',
    country_placeholder: 'اختر دولتك',
    about_life: 'عن حياتك',
    about_life_sub: 'تساعد بيانات الأسرة المعلنين على اقتراح المنتجات المناسبة',
    gender: 'الجنس',
    male: 'ذكر', female: 'أنثى', non_binary: 'غير ثنائي', prefer_not: 'أفضل عدم الإفصاح',
    rel_status: 'الحالة الاجتماعية',
    rel_placeholder: 'اختر',
    single: 'أعزب', in_rel: 'في علاقة', married: 'متزوج / شريك', divorced: 'مطلق / منفصل',
    employment: 'الحالة الوظيفية',
    student: 'طالب', employed_ft: 'موظف بدوام كامل', employed_pt: 'موظف بدوام جزئي',
    self_emp: 'عامل لحساب الخاص / مستقل', unemployed: 'عاطل', retired: 'متقاعد',
    household: 'حجم الأسرة',
    household_placeholder: 'عدد أفراد الأسرة',
    just_me: 'أنا فقط', two_people: 'شخصان', three_four: '3–4 أشخاص', five_plus: '5 أو أكثر',
    income: 'الدخل السنوي للأسرة',
    income_placeholder: 'اختر النطاق (اختياري)',
    interests_values: 'الاهتمامات والقيم',
    interests_sub: 'اختر على الأقل 2 من كل قسم',
    what_interests: 'ما الذي يثير اهتمامك؟',
    what_values: 'ما الذي تقدره أكثر في الحياة؟',
    lifestyle: 'أسلوب حياتك',
    lifestyle_sub: 'تساعد بيانات أسلوب الحياة العلامات التجارية على العثور على جمهورها المثالي',
    which_best: 'أيها يصفك أكثر؟',
    shop_freq: 'كم مرة تتسوق عبر الإنترنت؟',
    shop_placeholder: 'اختر التكرار',
    daily: 'يومياً تقريباً', weekly: 'عدة مرات أسبوعياً', monthly: 'عدة مرات شهرياً', rarely: 'نادراً',
    primary_device: 'جهازك الرئيسي',
    device_placeholder: 'اختر الجهاز',
    screen_time: 'وقت الشاشة اليومي',
    screen_placeholder: 'اختر وقت الشاشة',
    under_1h: 'أقل من ساعة', h_1_3: '1–3 ساعات', h_3_5: '3–5 ساعات', over_5h: 'أكثر من 5 ساعات',
    shopping_intent: 'التسوق ونية الشراء',
    shopping_sub: 'هذه هي البيانات الأكثر قيمة — تُطعم المزيد من الكلاب مباشرة! 🐕',
    where_shop: 'أين تفضل التسوق؟',
    buy_next: 'ما الذي من المرجح أن تشتريه في الأشهر الثلاثة القادمة؟',
    social_platforms: 'ما هي المنصات الاجتماعية التي تستخدمها؟',
    privacy_note: '🔒 لا تُباع بياناتك أبداً. تُستخدم فقط لعرض إعلانات أكثر صلة.',
    continue: 'متابعة',
    back: 'رجوع',
    start: 'ابدأ إطعام الكلاب! 🐕',
    saving: 'جارٍ الحفظ...',
    homebody: '🏠 مقيم بالمنزل', homebody_d: 'أحب الليالي الهادئة في المنزل',
    adventurer: '🧗 مغامر', adventurer_d: 'دائماً أبحث عن الإثارة',
    social_butterfly: '🦋 اجتماعي', social_butterfly_d: 'أحب التواجد مع الناس',
    wellness: '🧘 صحة وعافية', wellness_d: 'الصحة والوعي الذهني أولاً',
    career: '🚀 طموح مهني', career_d: 'طموح وموجّه نحو الأهداف',
    family: '👨‍👩‍👧 الأسرة أولاً', family_d: 'الأسرة هي كل شيء',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('fas_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('fas_lang', lang);
    const dir = LANGUAGES.find(l => l.code === lang)?.dir || 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key, vars = {}) => {
    const translations = TRANSLATIONS[lang] || TRANSLATIONS.en;
    let str = translations[key] ?? TRANSLATIONS.en[key] ?? key;
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(`{${k}}`, v);
    });
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}